/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.supermercadosenac;

import com.mycompany.supermercadosenac.dao.ProdutoDAO;
import com.mycompany.supermercadosenac.model.Produto;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eduardo.oesilva
 */
public class TelaProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaProduto
     */
    public TelaProduto() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduto = new javax.swing.JTable();
        btnCadastrarProduto = new javax.swing.JButton();
        radioBuscarCodigoProduto = new javax.swing.JRadioButton();
        btnExcluirProduto = new javax.swing.JButton();
        btnAlterarProduto = new javax.swing.JButton();
        btnBuscarProduto = new javax.swing.JButton();
        radioBuscarNomeProduto = new javax.swing.JRadioButton();
        txtBuscarProduto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Produto");

        tableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Nome", "Descrição", "Estoque", "Peso (kg)", "Preço unitário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableProduto);

        btnCadastrarProduto.setText("Cadastrar");
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBuscarCodigoProduto);
        radioBuscarCodigoProduto.setText("Por Código");
        radioBuscarCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBuscarCodigoProdutoActionPerformed(evt);
            }
        });

        btnExcluirProduto.setText("Excluir");
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });

        btnAlterarProduto.setText("Alterar");
        btnAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProdutoActionPerformed(evt);
            }
        });

        btnBuscarProduto.setText("Buscar");
        btnBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdutoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBuscarNomeProduto);
        radioBuscarNomeProduto.setSelected(true);
        radioBuscarNomeProduto.setText("Por nome");
        radioBuscarNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBuscarNomeProdutoActionPerformed(evt);
            }
        });

        txtBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarProdutoActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(radioBuscarNomeProduto)
                        .addGap(26, 26, 26)
                        .addComponent(radioBuscarCodigoProduto)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioBuscarNomeProduto)
                    .addComponent(radioBuscarCodigoProduto)
                    .addComponent(btnBuscarProduto)
                    .addComponent(btnCadastrarProduto)
                    .addComponent(btnAlterarProduto)
                    .addComponent(btnExcluirProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdutoActionPerformed
        
        //Caso o botão Nome esteja ativado
        if(radioBuscarNomeProduto.isSelected()){
            //caso a caixa esteja vazia - listará todos
            if(txtBuscarProduto.getText().length()==0){
                ArrayList <Produto> lista = ProdutoDAO.listar();
                DefaultTableModel modelo = (DefaultTableModel) tableProduto.getModel();
                modelo.setRowCount(0);
                
                for(Produto item : lista){
                    modelo.addRow(new String[]{String.valueOf(item.getIdProduto()),
                                               String.valueOf(item.getCodProduto()),
                                               String.valueOf(item.getNomeProduto()),
                                               String.valueOf(item.getDescricaoProduto()),
                                               String.valueOf(item.getQuantidadeProduto()),
                                               String.valueOf(item.getPesoProduto()),
                                               String.valueOf(item.getPrecoProduto())});
                }
                //caso tenha algum nome - listará todos que tiverem aquele texto no nome
            }else{
                String nome = "%"+txtBuscarProduto.getText()+"%";
                ArrayList <Produto> lista = ProdutoDAO.buscarPorNome(nome);
                
                DefaultTableModel modelo = (DefaultTableModel) tableProduto.getModel();
                modelo.setRowCount(0);
                for(Produto item : lista){
                    modelo.addRow(new String[]{String.valueOf(item.getIdProduto()),
                                               String.valueOf(item.getCodProduto()),
                                               String.valueOf(item.getNomeProduto()),
                                               String.valueOf(item.getDescricaoProduto()),
                                               String.valueOf(item.getQuantidadeProduto()),
                                               String.valueOf(item.getPesoProduto()),
                                               String.valueOf(item.getPrecoProduto())});
                }
            }
//Caso botão código esteja selecionado
        }else{
            //caso a caixa esteja vazia - listará todos
            if(txtBuscarProduto.getText().equals("")){
                ArrayList <Produto> lista = ProdutoDAO.listar();
                DefaultTableModel modelo = (DefaultTableModel) tableProduto.getModel();
                modelo.setRowCount(0);
                
                for(Produto item : lista){
                    modelo.addRow(new String[]{String.valueOf(item.getIdProduto()),
                                               String.valueOf(item.getCodProduto()),
                                               String.valueOf(item.getNomeProduto()),
                                               String.valueOf(item.getDescricaoProduto()),
                                               String.valueOf(item.getQuantidadeProduto()),
                                               String.valueOf(item.getPesoProduto()),
                                               String.valueOf(item.getPrecoProduto())});
                }
            }else{
                //caso tenha algum código - listará quem tiver aquele código
                String codigo = txtBuscarProduto.getText();
                ArrayList <Produto> lista = ProdutoDAO.buscarPorCodigo(codigo);
                
                DefaultTableModel modelo = (DefaultTableModel) tableProduto.getModel();
                modelo.setRowCount(0);
                for(Produto item : lista){
                    modelo.addRow(new String[]{String.valueOf(item.getIdProduto()),
                                               String.valueOf(item.getCodProduto()),
                                               String.valueOf(item.getNomeProduto()),
                                               String.valueOf(item.getDescricaoProduto()),
                                               String.valueOf(item.getQuantidadeProduto()),
                                               String.valueOf(item.getPesoProduto()),
                                               String.valueOf(item.getPrecoProduto())});
                }
            }
        }
        
    }//GEN-LAST:event_btnBuscarProdutoActionPerformed

    private void txtBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProdutoActionPerformed

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed
        int linhaSelecionada = tableProduto.getSelectedRow();
        int id = Integer.parseInt(tableProduto.getValueAt(linhaSelecionada,0).toString());

        String[] opcoes={"Sim, confirmar", "Não, cancelar"};
            
        int confirmar = JOptionPane.showOptionDialog(this,
                    "Confirmar exclusão?","Confirmação",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opcoes,opcoes[0]);
        
        if(confirmar==0){
            boolean retorno = ProdutoDAO.excluir(id);
            if(retorno){
                JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!");
            }else{
                JOptionPane.showMessageDialog(this, "Falha ao excluir o produto!");
            }
        }else{
             JOptionPane.showMessageDialog(this, "Exclusão cancelada");
        }
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void btnAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProdutoActionPerformed
        int linhaSelecionada = tableProduto.getSelectedRow();
        int id = Integer.parseInt(tableProduto.getValueAt(linhaSelecionada,0).toString());
        String codigo = tableProduto.getValueAt(linhaSelecionada,1).toString();
        String nome = tableProduto.getValueAt(linhaSelecionada,2).toString();
        String descricao = tableProduto.getValueAt(linhaSelecionada,3).toString();
        int quantidade = Integer.parseInt(tableProduto.getValueAt(linhaSelecionada,4).toString());
        double peso = Double.parseDouble(tableProduto.getValueAt(linhaSelecionada,5).toString());
        double preco = Double.parseDouble(tableProduto.getValueAt(linhaSelecionada,6).toString());
        
        
        Produto obj = new Produto(id,codigo, nome,descricao,quantidade,peso,preco);
        CadastroProduto janelaCadastroProduto = new CadastroProduto(obj);
        janelaCadastroProduto.setVisible(true);
    }//GEN-LAST:event_btnAlterarProdutoActionPerformed

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        
        
        CadastroProduto janelaCadastroProduto = new CadastroProduto();
        janelaCadastroProduto.setVisible(true);

    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void radioBuscarNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBuscarNomeProdutoActionPerformed
        txtBuscarProduto.setText(null);
    }//GEN-LAST:event_radioBuscarNomeProdutoActionPerformed

    private void radioBuscarCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBuscarCodigoProdutoActionPerformed
        txtBuscarProduto.setText(null);
    }//GEN-LAST:event_radioBuscarCodigoProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarProduto;
    private javax.swing.JButton btnBuscarProduto;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioBuscarCodigoProduto;
    private javax.swing.JRadioButton radioBuscarNomeProduto;
    private javax.swing.JTable tableProduto;
    private javax.swing.JTextField txtBuscarProduto;
    // End of variables declaration//GEN-END:variables
}
